services:
  yolo_api:
    build: .
    volumes:
      - .:/app
    ipc: host
    ports:
      - "4000:4000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              options:
                optional: true # GPU requirement optional
