services:
  yolo_api:
    build: .
    volumes:
      - .:/app
    ipc: host
    ports:
      - "4000:4000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
